version: "3.9"

services:
  server:
    build: ./server
    container_name: idaas-server
    restart: always
    ports:
      - "5000:5000"
    environment:
      # Prisma database connection (Postgres)
      DATABASE_URL: postgres://postgres:postgres@db:5432/idaas
      NODE_ENV: production
    depends_on:
      - db
    volumes:
      - ./server:/app
      - /app/node_modules

  db:
    image: postgres:15-alpine
    container_name: idaas-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: idaas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
