name: Deploy main-app
on:
  push:
    paths:
      - "client/main-app/**"
      - ".github/workflows/deploy-main.yml"
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install & build
        working-directory: client/main-app
        run: |
          npm ci
          echo "VITE_API_URL=${{ secrets.API_URL }}" >> .env.production
          npm run build

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: |
          aws s3 sync client/main-app/dist s3://${{ secrets.S3_BUCKET_MAIN }} --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CF_DIST_ID_MAIN }} \
            --paths "/*"
