name: Deploy admin-app

on:
  push:
    paths:
      - "client/admin-app/**"
      - ".github/workflows/deploy-admin.yml"
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # required for GitHub OIDC to AWS
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies & build
        working-directory: client/admin-app
        run: |
          npm ci
          echo "VITE_API_URL=${{ secrets.API_URL }}" >> .env.production
          npm run build

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: |
          aws s3 sync client/admin-app/dist s3://${{ secrets.S3_BUCKET_ADMIN }} --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CF_DIST_ID_ADMIN }} \
            --paths "/*"
